stages:
  - build
  - deploy

maven-build:
  image: maven:3.6.3-openjdk-11
  stage: build
  before_script:
      - export M2_HOME=/opt/maven
      - export MAVEN_HOME=/opt/maven
      - export PATH=${M2_HOME}/bin:${PATH}
  script:
      - mvn clean package
  after_script:
      - mv /data/deploy/dev/app.jar /data/deploy/dev/backup/app.jar_$(date '+%Y%m%d%H%M%S') || true
      - mv target/backend-0.0.1-SNAPSHOT.jar /data/deploy/dev/app.jar

deploy-server:
    stage: deploy
    before_script:
      - export imagename=10.123.202.171:5000/sf-app
      - export imagetag=v$(date '+%Y%m%d')
      - docker build -t sf-app:$imagetag /data/deploy/dev
      - docker tag sf-app:$imagetag $imagename:$imagetag
      - docker push $imagename:$imagetag
      - docker rmi $imagename:$imagetag
      - docker rmi sf-app:$imagetag
    script:
      - export sshscript='ssh sfuser@10.123.202.201 -p 2211'
      - $sshscript docker pull $imagename:$imagetag
      - $sshscript docker stop sf-app || true
      - $sshscript docker rm sf-app || true
      - $sshscript docker run --name sf-app -d -p 8080:8080 $imagename:$imagetag $APP_ENV_DEV
      - export rmiscript='ssh sfuser@10.123.202.201 -p 2211 docker rmi $(docker images -q --filter "before='$imagename':'$imagetag'") || true'
      - $rmiscript