#####공통 설정#####
spring:
  #log색상지정
  output:
    ansi:
      enabled: always
  gatewayUrl: http://localhost:9999

  #servlet 설정
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 100MB

# jasypt bean regist : 프로퍼티 암호화 기능 관련 복호화 처리
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
  key: "857b2405e94125f026da8aecb65ad1616bcf336ae827b549146a83cfc17bcbeb79253b61f016fac169e5cf033d470c319afa591224c1cbb84450aa08bf7cf372" #256 bits이상 (default: kfems)
#
jwt:
  cookieId: "FEMS_SESSION"
  secretKey: "32cdd8f65ec9344d3394dde288d0c8133f9dc7b783709a2e3fbe44285d4596d522e99506422f14d66187ea2c56d1542573922fff697a9915817b95f85bc34336" #256 bits이상 (default: secretKeysecretKeysecretKeysecretKeysecretKeysecretKey)
  tokenValidTime: -1 #분단위 (default: 30)

#We can use the httpOnly and secure flags to secure our session cookie:
#
#httpOnly: if true then browser script won't be able to access the cookie
#secure: if true then the cookie will be sent only over HTTPS connection
server:
  #port설정
  port: 8080
  error:
    #에러표시여부
    include-exception: false
    #handler path
    path: /error
    # 기본처리사용여부
    whitelabel:
      enabled: false
  servlet:
    encoding: 
      charset: UTF-8
      force: true
    session:
      cookie:
        http-only: true
#        secure: true
# 아래 max-swallow-size 쓸건지 여부는 판단해야함. 
#  tomcat:
#    max-swallow-size: 100MB

#
restTemplate:
  factory:
    connectTimeout: 3000
    readTimeout: 5000 
  httpClient:
    maxConnPerRoute: 5 
    maxConnTotal: 100

#mybatis
mybatis:
  configuration:
    default-executor-type: reuse
    lazy-loading-enabled: true
    map-underscore-to-camel-case: true
    use-generated-keys: true
  mapper-locations: classpath*:sqlmap/**/${spring.datasource.db-type}/**/**.xml
  type-aliases-package: com.lsitc.core.base

#로깅관련
logging:
  config: classpath:logback_spring.xml

file:
  allowType: xlsx,ppt,pptx,doc,docx,pdf,hwp,csv,txt,wav,avi,mp3,mpeg,bmp,jpg,jpeg,png,gif,au,ogg,dwg,XLSX,PPT,PPTX,DOC,DOCX,PDF,HWP,CSV,TXT,WAV,AVI,MP3,MPEG,BMP,JPG,JPEG,PNG,GIF,AU,OGG,DWG
  allowMimeType: application/zip,application/msword,application/pdf,application/x-hwp,applicaion/haansofthwp,application/x-tika-msoffice,application/x-tika-ooxml,image,text,application/vnd.ms-word,application/vnd.ms-excel,application/vnd.ms-powerpoint,application/vnd.openxmlformats-officedocument,applicaion/vnd.hancom

--- 
#####local환경#####
spring:
  config:
    activate:
      on-profile: local
  #datasource-maria
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy #logging SQL
    url: jdbc:log4jdbc:mariadb://192.168.0.151/fems
    username: femsadmin
    password: fems2021!
    hikari:
        minimum-idle: 1
        maximum-pool-size: 3
        idle-timeout: 600000 #(10분)
        max-lifetime: 1800000 #(30분)
        connection-timeout: 15000 

#파일관련 
file:
  filePath: c:\tmp\real
  fileTmpPath: c:\tmp\tmp

#로깅관련  
logging:
  file:
    path: c:\tmp\logs
    max-size: 10MB
    max-history: 7
  level: 
    root: DEBUG
  loginLogEnable: false
  menuCnctLogEnable: false

#서버포트 설정
server:
  error:
    #stactrcae포함
    include-stacktrace: always

--- 
#####운영 환경#####
spring:
  config:
    activate:
      on-profile: prod

#
file:
  filePath: D:\bgrEms\files\real
  fileTmpPath: D:\bgrEms\files\tmp

#logging  
logging:
  file:
    path: D:\bgrEms\logs
    max-history: 30
    max-size: 100MB
  level: 
    ROOT: INFO
  loginLogEnable: true #로그인 로그 여부
  menuCnctLogEnable: true #메뉴 로그 여부
    
#서버포트 설정
server:
  error:
    #stactrcae포함
    include-stacktrace: never
      
--- 
#####운영 환경#####
spring:
  config:
    activate:
      on-profile: docker

#
file:
  filePath: /tmp/files/real
  fileTmpPath: /tmp/files/tmp

#logging  
logging:
  file:
    path: /tmp/logs
    max-history: 30
    max-size: 100MB
  level: 
    ROOT: INFO
  loginLogEnable: true #로그인 로그 여부
  menuCnctLogEnable: true #메뉴 로그 여부
    
#서버포트 설정
server:
  error:
    #stactrcae포함
    include-stacktrace: never

---
spring:
  config:
    activate:
      on-profile: cloud
  #datasource-maria 
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy #logging SQL
    url: jdbc:log4jdbc:mariadb://192.168.0.151/fems
    username: femsadmin
    password: fems2021!
    hikari:
        minimum-idle: 3
        maximum-pool-size: 10
        idle-timeout: 600000 #(10분)
        max-lifetime: 1800000 #(30분)
        connection-timeout: 15000 
    
#파일관련 
file:
  filePath: /tmp/real
  fileTmpPath: /tmp/tmp

#로깅관련  
logging:
  file:
    path: /tmp/logs
    max-size: 10MB
    max-history: 7
  level: 
    root: DEBUG
  loginLogEnable: false
  menuCnctLogEnable: false

#서버포트 설정
server:
  error:
    #stactrcae포함
    include-stacktrace: always